### ISSUE TITLE
[Bug] Not Working with requests prepare

### ISSUE THREAD

**Issue by Kenith** [requests/requests-ntlm#102]
Hello,

We found that the requests-ntlm not working with requests prepare.

Not Working if you write as this:

```
import requests
from requests_ntlm import HttpNtlmAuth

session = requests.Session()
session.auth = HttpNtlmAuth('GLOBAL\\***', '***')
session.verify = False

req = requests.Request('GET', 'https://***.corp.***.com/owa/')
res = session.send(req.prepare())

print res.status_code
print res.content
```

Working with following:
```
import requests
from requests_ntlm import HttpNtlmAuth

session = requests.Session()
session.auth = HttpNtlmAuth('GLOBAL\\***', '***')
session.verify = False

res = session.get('https://***.corp.***.com/owa/')

print res.status_code
print res.content
```

**Comment by dassio** [comment]
have you tried to use `res = session.send(session.prepare_request(req))` , i see from [here](http://docs.python-requests.org/en/master/user/advanced/), `req.prepare()` way seems to lost session-level state. i do not have a NTLM server around will try it later.

**Comment by sigmavirus24** [comment]
@dassio is correct. The correct way to utilize session-level authentication is to use `session.prepare_request`. Based on your sample code, however, it's not apparent you need to use such a low-level function.
