### ISSUE TITLE
Unsupported hash type 'md4' on Ubuntu 22

### ISSUE THREAD

**Issue by mohan78** [requests/requests-ntlm#127]
We are using this project to perform authentication. Recently, we thought of upgrading the ubuntu distro we are using to 22 (jammy). After we upgrade the distro, we are getting an error "Unsupported hash type 'md4'" from hashlib inside `ntlm-auth`. Is there any work-around or known solution to this issue?

Thanks in advance.

**Comment by eusoubrasileiro** [comment]
For ubuntu jammy 22.04 Solution is this https://bugs.launchpad.net/ubuntu/+source/python3.10/+bug/1971580/comments/3

Add this to your `/usr/lib/openssl.cnf` to 're-enable' md4 to hashlib

```
[provider_sect]
default = default_sect
legacy = legacy_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1
```

**Comment by jborean93** [comment]
Fixed by https://github.com/requests/requests-ntlm/pull/126
