### ISSUE TITLE
About multiple independent connections to same host

### ISSUE THREAD

**Issue by exvito** [requests/requests-ntlm#56]
Hi,

First of all, thanks for sharing the package which works great in a single-connection-at-a-time scenario. :)

I'm in a scenario where I need two (or more) NTLM authenticated independent connections to the same host. These are requests to a REST interface with different URLs, say http://host/url_A?q_A and http://host/url_B?q_B.

My testing shows that these somewhat parallel requests sometimes work and other times get 401s. Following some investigation and digging through the code (both requests-ntlm and requests) I learned that:
* NTLM authentication is done on a per-connection basis.
* The auth process is completed after three request/responses on the connection.
* The currently published code does not ensure the same connection is reused (but pull request #51 does).
* The underlying requests (urllib3 actually) pool manager only returns connections from the pool on a hostname basis and not on a full-url basis.

This results in connections A (say for http://host/url_A?q_A) and B (for http://host/url_B?q_B) being switched along the three request/responses and, of course, leading to a failure.

If this is correct, would you have any suggestion on how to address my challenge? (I tried to investigate the possibility of providing an alternate pool manager implementation to urllib3 and did not find it... is there any?)

If my understanding is wrong, would you please point out my mistakes?

Thanks in advance for your feedback.

**Comment by Lukasa** [comment]
Your understanding is right. This is a tricky scenario: if you need authentication on a more finely-grained level than hostname, you'll need to override urllib3's connection pooling logic to understand that. That's a tricky thing, but do-able.

The slightly easier thing to do would be to use one session per authentication identity, and then the code in #51. That way you can hang the authentication off the session and ensure that you never get the wrong one, at the cost of slightly reduced connection pooling efficiency.

**Comment by exvito** [comment]
Thanks for your feedback.

I couldn't take the "slightly easier" approach in my case and went instead for the "replace the pool manager" version.

The steps I took:
* Create a pool manager with a different behaviour.
* Create a requests HTTP adapter that uses a that pool manager.
* Mount it in the session.

Seems to work nicely. I'll leave it below, for posterity.

```python
#!/usr/bin/env python

import logging
import urlparse

import requests


class PerFullURLPoolManager(requests.packages.urllib3.poolmanager.PoolManager):

    def connection_from_url(self, url):
        # Adapted from PoolManager.connection_from_host.
        # Difference: pool_key=url instead of (scheme, host, port)
        if not url:
            raise LocationValueError("No url specified.")
        pool_key = url
        with self.pools.lock:
            pool = self.pools.get(pool_key)
            if pool:
                return pool
            up = urlparse.urlparse(url)
            pool = self._new_pool(up.scheme, up.hostname, up.port)
            self.pools[pool_key] = pool
        return pool


class PerFullURLHTTPAdapter(requests.adapters.HTTPAdapter):

    def init_poolmanager(self, connections, maxsize, block=False, **pool_kwargs):
        # Adapted from HTTPAdapter.init_poolmanager.
        # Difference: poolmanager class.
        self._pool_connections = connections
        self._pool_maxsize = maxsize
        self._pool_block = block
        self.poolmanager = PerFullURLPoolManager(
                                num_pools=connections,
                                maxsize=maxsize,
                                block=block,
                                strict=True,
                                **pool_kwargs
                            )


if __name__ == '__main__':

    logging.basicConfig(level=logging.DEBUG)

    s = requests.Session()

    # Use a different connection pool per URL.
    # Comment these out and connections are pooled on a scheme/host/port basis.
    a = PerFullURLHTTPAdapter()
    s.mount('http://', a)
    s.mount('https://', a)

    # Will generate six connections with PerFullURLHTTPAdapter.
    # Or a single one with the default HTTPAdapter.
    s.get('http://127.0.0.1:8080/a')
    s.get('http://127.0.0.1:8080/b')
    s.get('http://127.0.0.1:8080/a?qa1')
    s.get('http://127.0.0.1:8080/b?qb1')
    s.get('http://127.0.0.1:8080/a?qa2')
    s.get('http://127.0.0.1:8080/b?qb2')
```

What's left: testing this with my NTLM authenticating code. I'll have a go at it later, when I have access to the systems requiring it.

Again, thanks for your feedback and support.

**Comment by Lukasa** [comment]
Glad to hear you were able to get something working!

**Comment by Lukasa** [comment]
Please feel free to close this if your testing reveals that everything is now functioning.

**Comment by exvito** [comment]
Just to let you know that I applied the approach above to my existing codebase, along with NTLM authentication: it works nicely, both with and wthout #51.

Without #51 I'm seeing two different connections per authentication (thus, per application level request). With #51 it seems to behave much better, fully reusing the connections.

Question: What's blocking the merge of #51? May I contribute somehow?

Thanks again.

**Comment by Lukasa** [comment]
#51 is in a tricky place. Firstly, it's got some outstanding code review notes on it. Secondly, there's some subtlety about what it does with closing connections that really needs to be sorted out. Feel free to take the patch and use it as a basis for that conversation. =)

**Comment by exvito** [comment]
I just did that. Closing the issue.
Again, thanks.
