### ISSUE TITLE
Push new release

### ISSUE THREAD

**Issue by Lukasa** [requests/requests-ntlm#60]
@sigmavirus24, turns out I'm not credentialed to push a new release of requests_ntlm, mind if you do it?

**Comment by sigmavirus24** [comment]
I actually can't push a release either. So this is up to @mastahyeti

**Comment by mastahyeti** [comment]
[Here's](https://pypi.python.org/pypi/requests_ntlm/0.2.0) the release. Let me know if you'd like your usernames added to the PyPi package.

**Comment by sigmavirus24** [comment]
@mastahyeti feel free to add graffatcolmingov to the PyPI package.

**Comment by mastahyeti** [comment]
Done.
