### ISSUE TITLE
using currently logged in user's credentials?

### ISSUE THREAD

**Issue by tkossak** [requests/requests-ntlm#66]
Is there a way to authenticate with currently logged user's credentials instead of providing login/password directly inside the script?

Thank you for this package, it works beautifully.

**Comment by Lukasa** [comment]
Not as far as I know. I think you should check whether we can signal that to the underlying NTLM library: if we can, then we can investigate whether we should expose that here.

**Comment by Lukasa** [comment]
Oh, and thanks for saying thanks! I'm glad it works well for you! (I'm on my phone, so I missed that comment.) :sparkles:
