### ISSUE TITLE
Support for Strict CbtHardeningLevel

### ISSUE THREAD

**Issue by jborean93** [requests/requests-ntlm#75]
Hi

I am trying to use Ansible with pywinrm to connect to your Windows hosts and have come across an issue with my company's environment. By default all our region's GPO policy's set the CbtHardeningLevel to Strict expect for our development region. Unfortunately python-ntlm3 requests-ntlm and pywinrm do not support this feature making it a no go for me and others that use Windows in our environment.

I've had a very brief play with editing python-ntlm3 to support this going by what I read on a ruby project that has added support for this security feature https://github.com/WinRb/rubyntlm/issues/27 but I am fairly new to Python and this is largely out of my depth. I also don't know if this library is still active and in development.

There is a library by @ianclegg https://github.com/ianclegg/ntlmlib that says supports CBT but the code for this seems to not be fully there (https://github.com/ianclegg/ntlmlib/blob/master/ntlmlib/authentication.py line 181) so I am not sure on the status.

Is there anyone that would be able to help me get this added as I feel like this would be a importance feature for large to enterprise companies to adopt Ansible. I apologise in advanced wiht my lack of skills but I am happy to help out where I can.

Extra Notes:
Channel Binding Tokens Info - https://msdn.microsoft.com/en-us/library/dd639324.aspx

**Comment by Lukasa** [comment]
I suspect this would be a valuable feature, but as you've mentioned, it is currently outside the scope of this library. We use dependencies to manage the NTLM auth procedure itself, so you'll need to discuss with them about adding this feature.

You may find it would be helpful to pay one of the developers on those projects to add the functionality you need: otherwise, you'll probably end up needing to do the bulk of the work yourself.

**Comment by ianclegg** [comment]
@jborean93 https://github.com/ianclegg/winrmlib/ is an (almost) drop in replacement for pywinrm which uses ntlmlib - it also offers credssp auth which is solves the double hop issue most people hit. If you want CBT in ntlmlib, raise an issue on ntlmlib tracker and we can discuss there.

I've implemented CBT before for an enterprise client before. If you want to have a go yourself the escalation engineers over dochelp@microsoft.com are very helpful. Obaid is an expert in CBT and Jeff McCashland is very helpful too.
Obaid's blog should be good enough to develop an implementation
https://blogs.msdn.microsoft.com/openspecification/2013/03/26/ntlm-and-channel-binding-hash-aka-extended-protection-for-authentication/

**Comment by jborean93** [comment]
Just an update on this, I have created a pull request https://github.com/trustrachel/python-ntlm3/pull/21 to add both NTLMv2 support (required for CBT) and CBT functionality. This will require some changes to requests-ntlm to support but it won't be anything major.
