### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by rbcarson** [requests/requests-ntlm#76]
Please make a new release for the changes in #73. Thanks!

**Comment by jborean93** [comment]
@Lukasa don't mean to be annoying here but is there a normal process to creating a release. Do you usually wait a few weeks before doing it?

**Comment by Lukasa** [comment]
@jborean93 I normally wait a brief period of time in the hope that anyone who is working against master will spot the most egregious problems, and that the changes can bake.

However, I have a todo item for a release next week.

**Comment by jborean93** [comment]
Thanks for the info, let me know if you need anything from me.
