### ISSUE TITLE
Change NTLM dependency

### ISSUE THREAD

**Issue by jborean93** [requests/requests-ntlm#77]
Hi

I have had a pull request open for around 18 days to update python-ntlm3 to support the extra security features of NTLM that were missing but it so far hasn't been looked at. This pull request will fix the issues raised https://github.com/requests/requests-ntlm/issues/71 and https://github.com/requests/requests-ntlm/issues/75.

After trying to get in contact with the maintainer and also talking to @sigmavirus24 I haven't been able to get some traction with the maintainer. I am proposing I or someone else create a new repository based on my changes of python-ntlm3 and create a new pypi package for requests-ntlm to use. Currently without any modifications to my changes it is a drop dead replacement but I would prefer to remove some deprecated methods if we go this route and update requests-ntlm to support the new method which brings NTLMv2, Channel Binding Tokens and SPEGNO encryption support.

Thanks

Jordan

**Comment by jborean93** [comment]
Just an update to this, I have gone ahead and made a pull request that changes the python-ntlm3 dependency to ntlm-auth which has all the features I tried to put in with the pull request to python-ntlm3.

The pull request for this is here https://github.com/requests/requests-ntlm/pull/79

**Comment by sigmavirus24** [comment]
Hi @jborean93 changing dependencies is not something we do lightly. If we do change libraries, it will need to be a longer deprecation cycle than what you waited for in having your pull request merged. I'm going to see if I can get in touch with Rachel again.

**Comment by jborean93** [comment]
Sounds fair, let me know how you go with this.

**Comment by jborean93** [comment]
@sigmavirus24 any luck with this?
