### ISSUE TITLE
Correct flags should be passed to python-ntlm3 when no domain is used

### ISSUE THREAD

**Issue by oliparcol** [requests/requests-ntlm#82]
Hello,

When there is no domain in the login (e.g. ``\\mylogin``), the flag ``ntlm.NTLM_TYPE1_FLAGS & ~ntlm.NTLM_NegotiateOemDomainSupplied`` should be passed to the ``create_NTLM_NEGOTIATE_MESSAGE`` function. Without this flag, the authentication fails.

Thank you,

**Comment by Lukasa** [comment]
Thanks for this suggestion! So I note that you've placed a patch in your fork but haven't submitted it as a PR. Any reason for that?

**Comment by oliparcol** [comment]
Sorry, I just created the PR.
