### ISSUE TITLE
UPN (kerberos-style) usernames and domain

### ISSUE THREAD

**Issue by slukovic** [requests/requests-ntlm#85]
Hi,

I have to connect to a mail server (Exchange) where emails are used as usernames. At the moment `HttpNtlmAuth` constructor finds `@` in my username [here](https://github.com/requests/requests-ntlm/blob/master/requests_ntlm/requests_ntlm.py#L31) and splits it into a domain and username pair.

This was added in @nitzmahone's pull request https://github.com/requests/requests-ntlm/pull/68.

In this particular case this is incorrect as domain should be empty. But it may also be incorrect in the general case. According to [this](http://davenport.sourceforge.net/ntlm.html#nameVariations), domain should always be empty when username is in kerberos-style format.

It is easy to work around this as I can change domain after `HttpNtlmAuth` was constructed. But should we add optional `domain` parameter to the constructor and/or not split usernames?

Regards,
Srdan

```
λ pip freeze | grep ntlm
ntlm-auth==1.0.2
requests-ntlm==1.0.0
```

**Comment by Lukasa** [comment]
Ultimately, I'm not sure.

The document you linked points out that there is an unavoidable ambiguity here: there are multiple possible parsing variations that ultimately look the same and cannot be reliably distinguished. That does rather suggest that taking an optional `domain` parameter in the constructor would be the way to go.

I'd be open to merging a PR that adds that functionality.

**Comment by slukovic** [comment]
Hi guys,

I pushed a provisional commit. I left two comments there. I wasn't sure about backwards compatibility of `__init__` and what should be the default domain.

**Comment by jborean93** [comment]
The v1.1.0 release contains the fix for correctly parsing UPN usernames.
