### ISSUE TITLE
Jupyter:"No module named requests_ntlm" (Still working with sublime)

### ISSUE THREAD

**Issue by tightdelay** [requests/requests-ntlm#93]
When I use 
> from requests_ntlm import HttpNtlmAuth"
the code works fine in Sublime.

But when I try the same code in Jupyter, it gives the following error:

> ImportError: No module named requests_ntlm

Any Ideas?

**Comment by Lukasa** [comment]
Sounds like whatever Python environment you installed requests-ntlm is different to the one you installed Jupyter into. Find whatever Python environment you installed Jupyter into and use `pip` to install requests-ntlm into the same one.
