### ISSUE TITLE
NTLM Auth Over SSL

### ISSUE THREAD

**Issue by H5a337230** [requests/requests-ntlm#95]
Hi
I have tried to connect to website using this package over ssl and used below code.

```
from urllib3.contrib import pyopenssl
import requests.packages.urllib3
from requests_ntlm import HttpNtlmAuth
...
requests.packages.urllib3.disable_warnings()
pyopenssl.inject_into_urllib3()
....
...
session = requests.Session()
					session.headers.update({'User-Agent': 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)'})
					session.auth = HttpNtlmAuth(userFile[unum],passFile[pnum], session)
					resp = session.get(addr , verify = False)
```

but I get below error.
`bad handshake: SysCallError(-1, 'Unexpected EOF')`

also I tried with custom HTTPAdapter and again that error
Any suggestion?

**Comment by Lukasa** [comment]
There is no need to call `inject_into_urllib3` yourself: Requests will call it for you.

Otherwise, this error means that the remote server is refusing our TLS connection attempt, likely because we don't support the same cipher suites it does. Is the server you're contacting publicly reachable? If not, you might want to try enabling 3DES [as shown in this blog post](https://lukasa.co.uk/2017/02/Configuring_TLS_With_Requests/).

**Comment by H5a337230** [comment]
I tried with different context and CTX_ciphers but it gives me certificate verify error (in code: verify = true) and also i tried with server certificate.

Yeap, its publicly reachable

**Comment by Lukasa** [comment]
If you're getting verification errors that's a step forward: it means the server is getting far enough to show us a certificate, and we don't like it.

Can you give me the hostname? I want to check the server.

**Comment by H5a337230** [comment]
sorry, for security reasons i can not give you hostname but you can tell me what i should to do

**Comment by H5a337230** [comment]
here is the full error
`bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)`

**Comment by Lukasa** [comment]
That error suggests that the TLS certificate isn't valid. If you run `openssl s_client -connect "host:port" -showcerts` and provide the output that would be helpful.

**Comment by H5a337230** [comment]
part of output:

```
SSL handshake has read 1447 bytes and written 605 bytes
---
New, TLSv1/SSLv3, Cipher is RC4-MD5
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : RC4-MD5
    Session-ID: C21300003C65FD2058F1AB766792E8825881B5F07D259177630A459E0B50CAD5
    Session-ID-ctx: 
    Master-Key: 09F4056A29739C8FB4DBA1B9E98C49516010D5FB96A7B614BB348299BF94EA3BD5BAB0B43CD1B769DB4E7E80E46795AC
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1499678606
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
```

**Comment by Lukasa** [comment]
Sorry, I need the big PEM blocks.

**Comment by H5a337230** [comment]
-----BEGIN CERTIFICATE-----
MIIFGzCCBAOgAwIBAgIQT3pARd9sigEDDHV0VdGaaDANBgkqhkiG9w0BAQsFADB+
MQswCQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAd
BgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxLzAtBgNVBAMTJlN5bWFudGVj
IENsYXNzIDMgU2VjdXJlIFNlcnZlciBDQSAtIEc0MB4XDTE1MDkxMzAwMDAwMFoX
DTE3MTAxMjIzNTk1OVowgZcxCzAJBgNVBAYTAk5QMRAwDgYDVQQIEwdCYWdtYXRp
MRIwEAYDVQQHFAlLQVRITUFORFUxLDAqBgNVBAoUI0NpdGl6ZW5zIEJhbmsgSW50
ZXJuYXRpb25hbCBMaW1pdGVkMRYwFAYDVQQLFA1JVCBEZXBhcnRtZW50MRwwGgYD
VQQDFBN3d3cuY3R6bmJhbmsuY29tLm5wMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEArCP0qxF+2h2iWZNoR161Ub3B8ikUrZdd+zajbokEc1jYikmtRa7B
4h7lbAZjT/UHktrGfnbfqDtkthudu/4ycvaD9JLqp+on0LJUWhShwDCSS2JRzYUF
6HGgrQkopEl4jfhPobEz4LbIl8rOr6TtgK3YS/lhktHvDyc0LAKGItdziFnhDSua
IX/a/AJe0Fjk6qU97hzGwmBdnQ8qwc5rqy75WXbG97YHCJ1J7ijQiKi5TYUrzeo/
ip6cZb2VbWOVgNZzkDBnRd7yMvxZpkY3KfPdB8S1jGwAEq02W/8enb6WwmeecIRo
1fUkvBTLRe2KWHa0fGivVNWz1u5LtMhu2wIDAQABo4IBeTCCAXUwLwYDVR0RBCgw
JoITd3d3LmN0em5iYW5rLmNvbS5ucIIPY3R6bmJhbmsuY29tLm5wMAkGA1UdEwQC
MAAwDgYDVR0PAQH/BAQDAgWgMGEGA1UdIARaMFgwVgYGZ4EMAQICMEwwIwYIKwYB
BQUHAgEWF2h0dHBzOi8vZC5zeW1jYi5jb20vY3BzMCUGCCsGAQUFBwICMBkMF2h0
dHBzOi8vZC5zeW1jYi5jb20vcnBhMCsGA1UdHwQkMCIwIKAeoByGGmh0dHA6Ly9z
cy5zeW1jYi5jb20vc3MuY3JsMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
AjAfBgNVHSMEGDAWgBRfYM9hkFXfhEMUimAqsvV69EMY7zBXBggrBgEFBQcBAQRL
MEkwHwYIKwYBBQUHMAGGE2h0dHA6Ly9zcy5zeW1jZC5jb20wJgYIKwYBBQUHMAKG
Gmh0dHA6Ly9zcy5zeW1jYi5jb20vc3MuY3J0MA0GCSqGSIb3DQEBCwUAA4IBAQBb
j3ubehFfUXcUK3RmgwQhGxX9Hda0+194N7FTSwC+z0WoJDhHD0q1HKWv7fNVKumn
qqzGdid5HMjrvqcRTyfPB0VnXr12rdSxmjd2BBB+caIbgkNTPd3tDNjzfSFro/Wb
r+/TlN0sv9K9K1o0kzKB/e9TWChD0wNwem+0r2oZhlG2JyOCLOm6fbzGEGlanRtZ
D8mhT6D09m7HKv+j0NdMVxQ2hR4ILIhktrikKm1CdKjL3ZhQzYIXpfhYJZpDAKjF
VRxcHzCVdBRWi/x/xU5B3AvOheLZ6KHMCoiLGuv7FIBfM2hNDENyswzLmmw6nbYa
67LnDwSYwJMYX+S8DmBK
-----END CERTIFICATE-----

**Comment by Lukasa** [comment]
Can you try adding `verify=certifi.old_where()`? You'll need to `import certifi` as well.

**Comment by H5a337230** [comment]
checked
again error
`bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)`

**Comment by Lukasa** [comment]
Hrm. How many certs is the server sending?

**Comment by H5a337230** [comment]
can it be because of the user-agent that i am using?

**Comment by Lukasa** [comment]
No, the user-agent isn't sent until after the TLS handshake completes.

**Comment by Lukasa** [comment]
I think the remote server is sending an incomplete cert chain.

**Comment by H5a337230** [comment]
Its just one cert and then closed with error
`read:errno=104
`

**Comment by Lukasa** [comment]
Yup, so I think this is an incomplete cert chain: we're missing some intermediates. Can you copy the file that is at the path provided by `python -c 'import certifi; print(certifi.old_where())'` to somewhere, then open that file and add this to the bottom?

```
-----BEGIN CERTIFICATE-----
MIIFODCCBCCgAwIBAgIQUT+5dDhwtzRAQY0wkwaZ/zANBgkqhkiG9w0BAQsFADCB
yjELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQL
ExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJp
U2lnbiwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxW
ZXJpU2lnbiBDbGFzcyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0
aG9yaXR5IC0gRzUwHhcNMTMxMDMxMDAwMDAwWhcNMjMxMDMwMjM1OTU5WjB+MQsw
CQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAdBgNV
BAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxLzAtBgNVBAMTJlN5bWFudGVjIENs
YXNzIDMgU2VjdXJlIFNlcnZlciBDQSAtIEc0MIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAstgFyhx0LbUXVjnFSlIJluhL2AzxaJ+aQihiw6UwU35VEYJb
A3oNL+F5BMm0lncZgQGUWfm893qZJ4Itt4PdWid/sgN6nFMl6UgfRk/InSn4vnlW
9vf92Tpo2otLgjNBEsPIPMzWlnqEIRoiBAMnF4scaGGTDw5RgDMdtLXO637QYqzu
s3sBdO9pNevK1T2p7peYyo2qRA4lmUoVlqTObQJUHypqJuIGOmNIrLRM0XWTUP8T
L9ba4cYY9Z/JJV3zADreJk20KQnNDz0jbxZKgRb78oMQw7jW2FUyPfG9D72MUpVK
Fpd6UiFjdS8W+cRmvvW1Cdj/JwDNRHxvSz+w9wIDAQABo4IBYzCCAV8wEgYDVR0T
AQH/BAgwBgEB/wIBADAwBgNVHR8EKTAnMCWgI6Ahhh9odHRwOi8vczEuc3ltY2Iu
Y29tL3BjYTMtZzUuY3JsMA4GA1UdDwEB/wQEAwIBBjAvBggrBgEFBQcBAQQjMCEw
HwYIKwYBBQUHMAGGE2h0dHA6Ly9zMi5zeW1jYi5jb20wawYDVR0gBGQwYjBgBgpg
hkgBhvhFAQc2MFIwJgYIKwYBBQUHAgEWGmh0dHA6Ly93d3cuc3ltYXV0aC5jb20v
Y3BzMCgGCCsGAQUFBwICMBwaGmh0dHA6Ly93d3cuc3ltYXV0aC5jb20vcnBhMCkG
A1UdEQQiMCCkHjAcMRowGAYDVQQDExFTeW1hbnRlY1BLSS0xLTUzNDAdBgNVHQ4E
FgQUX2DPYZBV34RDFIpgKrL1evRDGO8wHwYDVR0jBBgwFoAUf9Nlp8Ld7LvwMAnz
Qzn6Aq8zMTMwDQYJKoZIhvcNAQELBQADggEBAF6UVkndji1l9cE2UbYD49qecxny
H1mrWH5sJgUs+oHXXCMXIiw3k/eG7IXmsKP9H+IyqEVv4dn7ua/ScKAyQmW/hP4W
Ko8/xabWo5N9Q+l0IZE1KPRj6S7t9/Vcf0uatSDpCr3gRRAMFJSaXaXjS5HoJJtG
QGX0InLNmfiIEfXzf+YzguaoxX7+0AjiJVgIcWjmzaLmFN5OUiQt/eV5E1PnXi8t
TRttQBVSK/eHiXgSgW7ZTaoteNTCLD0IX4eRnh8OsN4wUmSGiaqdZpwOdgyA8nTY
Kvi4Os7X1g8RvmurFPW9QaAiY4nxug9vKWNmLT+sjHLF+8fk1A/yO0+MKcc=
-----END CERTIFICATE-----
```

**Comment by H5a337230** [comment]
Ok, but I would appreciate it if you delete PEM block
thanks

**Comment by Lukasa** [comment]
There is nothing private in a certificate block: they contain no secret data.

**Comment by H5a337230** [comment]
I know its public but i think it contain hostname

**Comment by H5a337230** [comment]
BTW, Added. 
So, what now?

**Comment by Lukasa** [comment]
@H5a337230 Try again. =) You need whatever change you made to get the `certificate verify failed` error, then set `verify=/path/to/the/file/you/just/created` and see if that works.

**Comment by H5a337230** [comment]
![code](https://user-images.githubusercontent.com/28677572/28013486-204d6c8a-6561-11e7-9ff2-fd8ecf3cdf8c.png)
![resault](https://user-images.githubusercontent.com/28677572/28013492-27e39852-6561-11e7-972b-250a589968a0.png)

**Comment by Lukasa** [comment]
Did you add the PEM data I posted to that certifi bundle?

**Comment by H5a337230** [comment]
YEAP

**Comment by Lukasa** [comment]
Hrm. This is now extremely problematic. Try `openssl s_client -connect "host:port" -CApath /usr/local/lib/python2.7/dist-packages/certifi/weak.pem`

**Comment by H5a337230** [comment]
No difference from the previous one in result

**Comment by Lukasa** [comment]
Humor me and show me the output?

**Comment by H5a337230** [comment]
![resu](https://user-images.githubusercontent.com/28677572/28018659-08d1c32a-6576-11e7-96b4-3aa517450587.png)

**Comment by Lukasa** [comment]
Ideally in text form, and *all* the output if possible. Please also add `-showcerts`.

**Comment by Lukasa** [comment]
(You can leave out the PEM data, so long as you leave the `---BEGIN---` and `---END---` bits: I need to see where they are in the data.)

**Comment by H5a337230** [comment]
FIXED, The problem was on the server side [ server certificate ]
