### ISSUE TITLE
Comparison to ntlm3 usage?

### ISSUE THREAD

**Issue by chriscate** [requests/requests-ntlm#98]
Thanks for picking up and continuing the work of `ntlm3`! Question... I used to use `ntlm3` like this:

```
from ntlm3 import HTTPNtlmAuthHandler
from six.moves.urllib.request import BaseHandler, HTTPPasswordMgrWithDefaultRealm, build_opener


def auth_opener(url, username, password, ntlm=False):
    password_manager = HTTPPasswordMgrWithDefaultRealm()
    password_manager.add_password(None, url, username, password)
    if ntlm:
        auth_handler = HTTPNtlmAuthHandler.HTTPNtlmAuthHandler(password_manager)
    else:
        auth_handler = ...
    opener = build_opener(auth_handler)
    return opener
```

Can I achieve the same functionality with `requests_ntlm`?  If so, how? I've not been able to figure it out. Thanks!

**Comment by sigmavirus24** [comment]
@chriscate This is not a fork of `ntlm3`. This is a library that builds on top of it to provide NTLM authentication mechanisms for the Requests library.
